apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: skills-cluster
  region: ap-northeast-2
  version: "1.27"
  tags:
    karpenter.sh/discovery: skills-cluster

vpc:
  subnets:
    private:
      ap-northeast-2a:
        id: subnet-00d1a1d8e0617a454
      ap-northeast-2b:
        id: subnet-0f825320951bfc959
      ap-northeast-2c:
        id: subnet-03f923bc7f2ab3791

iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: karpenter
      namespace: karpenter
    roleName: skills-cluster-karpenter
    attachPolicyARNs:
      - arn:aws:iam::790946953677:policy/KarpenterControllerPolicy-skills-cluster
    roleOnly: true

iamIdentityMappings:
- arn: "arn:aws:iam::790946953677:role/KarpenterNodeRole-skills-cluster"
  username: system:node:{{EC2PrivateDNSName}}
  groups:
  - system:bootstrappers
  - system:nodes

managedNodeGroups:
  - instanceType: m5.large
    amiFamily: AmazonLinux2
    name: skills-cluster-ng
    desiredCapacity: 3
    minSize: 3
    maxSize: 16
    privateNetworking: true
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        externalDNS: true
        certManager: true
        appMesh: true
        appMeshPreview: true
        ebs: true
        fsx: true
        efs: true
        awsLoadBalancerController: true
        xRay: true
        cloudWatch: true

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]
