apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: skills-cluster
  region: ap-northeast-2
  version: '1.27'

iam:
  withOIDC: true

vpc:
  subnets:
    private:
      ap-northeast-2a:
        id: subnet-00d1a1d8e0617a454
      ap-northeast-2b:
        id: subnet-0f825320951bfc959
      ap-northeast-2c:
        id: subnet-03f923bc7f2ab3791

managedNodeGroups:
  - name: skills-nodegroup
    minSize: 3
    desiredCapacity: 3
    maxSize: 16
    instanceType: c5.large
    privateNetworking: true
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        externalDNS: true
        certManager: true
        appMesh: true
        appMeshPreview: true
        ebs: true
        fsx: true
        efs: true
        awsLoadBalancerController: true
        xRay: true
        cloudWatch: true

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]
