apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: skills-cluster
  region: ap-northeast-2
  version: "1.27"
  tags:
    karpenter.sh/discovery: skills-cluster

vpc:
  subnets:
    private:
      ap-northeast-2a:
        id: subnet-09ac73bc7db2ccfa0
      ap-northeast-2b:
        id: subnet-057477afbb4651e66
      ap-northeast-2c:
        id: subnet-0e7dd6e312bf0a3e7

privateCluster:
  enabled: true
  additionalEndpointServices:
    - autoscaling
    - cloudformation
    - logs

iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: karpenter
      namespace: karpenter
    roleName: skills-cluster-karpenter
    attachPolicyARNs:
      - arn:aws:iam::790946953677:policy/KarpenterControllerPolicy-skills-cluster
  - metadata:
      name: allowlist
    roleName: skills-allowlist-role
    attachPolicyARNs:
      - arn:aws:iam::790946953677:policy/skills-allowlist

iamIdentityMappings:
- arn: "arn:aws:iam::790946953677:role/KarpenterNodeRole-skills-cluster"
  username: system:node:{{EC2PrivateDNSName}}
  groups:
  - system:bootstrappers
  - system:nodes

managedNodeGroups:
  - instanceType: m5.large
    amiFamily: AmazonLinux2
    name: skills-cluster-ng
    desiredCapacity: 3
    minSize: 3
    maxSize: 16
    privateNetworking: true
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        externalDNS: true
        certManager: true
        appMesh: true
        appMeshPreview: true
        ebs: true
        fsx: true
        efs: true
        awsLoadBalancerController: true
        xRay: true
        cloudWatch: true

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]
