apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    app: user
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: 790946953677.dkr.ecr.ap-northeast-2.amazonaws.com/skills-user:latest
        env:
          - name: DB_WRITE_HOST
            value: skills-db.cluster-cadxb1cncc5b.ap-northeast-2.rds.amazonaws.com
          - name: DB_READ_HOST
            value: skills-db.cluster-ro-cadxb1cncc5b.ap-northeast-2.rds.amazonaws.com
          - name: DB_NAME
            value: dev
          - name: DB_USER
            value: skills
          - name: DB_PASSWORD
            value: '6]:<##V>UG0L25wAI?%qD[S4t+*&'
          - name: DB_PORT
            value: '5432'
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: allowlist
  labels:
    app: allowlist
spec:
  replicas: 3
  selector:
    matchLabels:
      app: allowlist
  template:
    metadata:
      labels:
        app: allowlist
    spec:
      containers:
      - name: allowlist
        image: 790946953677.dkr.ecr.ap-northeast-2.amazonaws.com/skills-allowlist:latest
        env:
          - name: GROUP_ID
            value: 
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: event
  labels:
    app: event
spec:
  replicas: 3
  selector:
    matchLabels:
      app: event
  template:
    metadata:
      labels:
        app: event
    spec:
      containers:
      - name: event
        image: 790946953677.dkr.ecr.ap-northeast-2.amazonaws.com/skills-event:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
