apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    app: user
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: 790946953677.dkr.ecr.ap-northeast-2.amazonaws.com/skills-ecr:latest
        env:
          - name: DB_WRITE_HOST
            value: skills-db.cluster-cadxb1cncc5b.ap-northeast-2.rds.amazonaws.com
          - name: DB_READ_HOST
            value: skills-db.cluster-ro-cadxb1cncc5b.ap-northeast-2.rds.amazonaws.com
          - name: DB_NAME
            value: dev
          - name: DB_USER
            value: skills
          - name: DB_PASSWORD
            value: 'GGdAz|vruMDs}:+fCd*6{aEEHw{~'
          - name: DB_PORT
            value: '5432'
        ports:
        - containerPort: 8080
