apiVersion: v1
kind: Service
metadata:
  name: user
spec:
  type: ClusterIP
  selector:
    app: user
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: allowlist
spec:
  type: ClusterIP
  selector:
    app: allowlist
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: event
spec:
  type: ClusterIP
  selector:
    app: event
  ports:
    - port: 8080
      targetPort: 8080

